---
- name: install httpd(apache)
  yum:  
    name: httpd
    state: latest
- name: start the apache server
  service:
    name: httpd
    state: started
- name: copy index.html file
  copy:
    src: index.html
    dest: /var/www/html/

